[project]
name = "exercise0-material"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "pattern>=0.0.1a0",
    "scipy>=1.16.3",
    "tabulate>=0.9.0",
]
